# -*- coding: utf-8 -*-
"""HandTraking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xm1vROe1Ec3YO8KdMCY0dzjXtW6ohk0P
"""



# MediaPipe
import cv2
import mediapipe as mp
import time

cap=cv2.VideoCapture(0)

mphands=mp.solutions.hands
hands=mphands.Hands(
  static_image_mode=False,
  max_num_hands=2,
  min_detection_confidence=0.5,
  min_tracking_confidence=0.5
)
DrawingUtils=mp.solutions.drawing_utils
PreviousTime=0
CurrentTime=0
while True:
  success,img,=cap.read()
  imgRGB=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
  result= hands.process(imgRGB)
  # print(result.multi_hand_landmarks)
  if(result.multi_hand_landmarks):
    for handLms in result.multi_hand_landmarks:
      for id,lm in enumerate(handLms.landmark):
        h,w,c=img.shape
        cx,cy=int(lm.x*w),int(lm.y*h)
        print(id,cx,cy)
        if id==0:
          cv2.circle(img,(cx,cy),15,(255,0,255),cv2.FILLED)
        # cv2.circle(img,(cx,cy),10,(255,100,255),cv2.FILLED)
      DrawingUtils.draw_landmarks(img,handLms,mphands.HAND_CONNECTIONS,
                                  DrawingUtils.DrawingSpec(color=(255,0,0),thickness=2,circle_radius=4),
                                  DrawingUtils.DrawingSpec(color=(0,255,0),thickness=2,circle_radius=2))    
 
  CurrentTime=time.time()
  FPS=1/(CurrentTime-PreviousTime)
  PreviousTime=CurrentTime
  cv2.putText(img,f'FPS:{int(FPS)}',(10,70),
              cv2.FONT_HERSHEY_SIMPLEX,1,(255,0,255),2)
  cv2.putText(img,f'Hands:{len(result.multi_hand_landmarks) if result.multi_hand_landmarks else 0}',
              (10,130),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),2)
  cv2.imshow("Image",img)  
  if cv2.waitKey(1) & 0xFF==ord('q'):
    break

