# -*- coding: utf-8 -*-
"""HandTraking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xm1vROe1Ec3YO8KdMCY0dzjXtW6ohk0P
"""


# MediaPipe
import cv2
import mediapipe as mp
import time

cap = cv2.VideoCapture(0)

mpFace = mp.solutions.face_detection

face_detection = mpFace.FaceDetection()

DrawingUtils = mp.solutions.drawing_utils
PreviousTime = 0
CurrentTime = 0
while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    result = face_detection.process(imgRGB)
    print(result)
    if result.detections:
        for _id, detection in enumerate(result.detections):
            # print(_id, detection)
            bboxC = detection.location_data.relative_bounding_box
            ih, iw, _ = img.shape
            x, y, w, h = (
                int(bboxC.xmin * iw),
                int(bboxC.ymin * ih),
                int(bboxC.width * iw),
                int(bboxC.height * ih),
            )
            cv2.rectangle(img, (x, y), (x + w, y + h), (10, 255, 0), 2)
    CurrentTime = time.time()
    FPS = 1 / (CurrentTime - PreviousTime)
    PreviousTime = CurrentTime
    cv2.putText(
        img, f"FPS:{int(FPS)}", (10, 70), cv2.FONT_HERSHEY_SIMPLEX, 1, (10, 255, 0), 2
    )
    cv2.imshow("Image", img)
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break
